### ISSUE TITLE
Parsing log file

### ISSUE THREAD

**Issue by akhikolla** [akhikolla/RcppDeepState#1]
Hello @tdhock,
Can you please help me parse this log file for inputs and error messages.
[use_after_deallocate_log.txt](https://github.com/akhikolla/RcppDeepState/files/4653559/use_after_deallocate_log.txt)

**Comment by tdhock** [comment]
hi @akhikolla here is some regex code that converts that log file to a data table with one row per error message,
```r
error.dt <- nc::capture_all_str(
  "use_after_deallocate_log.txt",
  "==[0-9]+==ERROR: ",
  sanitizer=".*?",
  ": ",
  error.type=".*?",
  " ",
  error.details=".*",
  "\n",
  trace="(?:.*\n)*?",
  "SUMMARY")
error.dt[, error.i := 1:.N]
error.dt[, src.file.lines := {
  file.line.dt <- nc::capture_all_str(
    one.trace,
    file.line="[^ ]+?:[0-9]+")
  file.line.dt[grepl("/src/", file.line), paste(file.line, collapse="\n")]
}, by=error.i]
count.dt <- error.dt[, .(
  count=.N
), by=.(sanitizer, error.type, src.file.lines)]
```
I get the following output:
```
> str(error.dt)
Classes ‘data.table’ and 'data.frame':	941 obs. of  6 variables:
 $ sanitizer     : chr  "AddressSanitizer" "AddressSanitizer" "AddressSanitizer" "AddressSanitizer" ...
 $ error.type    : chr  "alloc-dealloc-mismatch" "alloc-dealloc-mismatch" "alloc-dealloc-mismatch" "alloc-dealloc-mismatch" ...
 $ error.details : chr  "(operator new [] vs free) on 0x611000000040" "(operator new [] vs free) on 0x611000000040" "(operator new [] vs free) on 0x608000000020" "(operator new [] vs free) on 0x604000000010" ...
 $ trace         : chr  "    #0 0x4df910 in __interceptor_free.localalias.0 (/home/akhila/R/testASAN/use_after_deallocate_DeepState_Test"| __truncated__ "    #0 0x4df910 in __interceptor_free.localalias.0 (/home/akhila/R/testASAN/use_after_deallocate_DeepState_Test"| __truncated__ "    #0 0x4df910 in __interceptor_free.localalias.0 (/home/akhila/R/testASAN/use_after_deallocate_DeepState_Test"| __truncated__ "    #0 0x4df910 in __interceptor_free.localalias.0 (/home/akhila/R/testASAN/use_after_deallocate_DeepState_Test"| __truncated__ ...
 $ error.i       : int  1 2 3 4 5 6 7 8 9 10 ...
 $ src.file.lines: chr  "/home/akhila/R/testASAN/src/rcpp_use_after_deallocate.cpp:8\n/home/akhila/R/testASAN/src/rcpp_use_after_deallocate.cpp:6" "/home/akhila/R/testASAN/src/rcpp_use_after_deallocate.cpp:8\n/home/akhila/R/testASAN/src/rcpp_use_after_deallocate.cpp:6" "/home/akhila/R/testASAN/src/rcpp_use_after_deallocate.cpp:8\n/home/akhila/R/testASAN/src/rcpp_use_after_deallocate.cpp:6" "/home/akhila/R/testASAN/src/rcpp_use_after_deallocate.cpp:8\n/home/akhila/R/testASAN/src/rcpp_use_after_deallocate.cpp:6" ...
 - attr(*, ".internal.selfref")=<externalptr> 
> count.dt
          sanitizer             error.type
1: AddressSanitizer alloc-dealloc-mismatch
                                                                                                             src.file.lines
1: /home/akhila/R/testASAN/src/rcpp_use_after_deallocate.cpp:8\n/home/akhila/R/testASAN/src/rcpp_use_after_deallocate.cpp:6
   count
1:   941
> 
```
The `count.dt` is simple and probably the most helpful for the user because it shows exactly what files and line numbers in their code where they should look (src.file.lines), and tells them the error type (alloc-dealloc-mismatch) and number of times the error occured.

the error.dt keeps pretty much all of the error message in `trace` and these details may be helpful for the user in some cases.

Does that make sense / work for you?

**Comment by akhikolla** [comment]
Thanks, @tdhock that really helps a lot. 

Looks like you have mentioned one.trace in the code instead of the trace at this point. Shouldn't that be trace?

> file.line.dt <- nc::capture_all_str(
>     one.trace,
>     file.line="[^ ]+?:[0-9]+")

**Comment by tdhock** [comment]
right

**Comment by tdhock** [comment]
tell me if you need any help parsing the other logs

**Comment by akhikolla** [comment]
Hello @tdhock ,

I wrote the following regex for getting the input, file name, line number the error occurred from the log files.

https://github.com/akhikolla/RcppDeepState/blob/update-analyze-and-display-errors/R/errorrcode.R  

And the log files are present here: https://github.com/akhikolla/RcppDeepState/tree/update-analyze-and-display-errors/tests/testthat
Please do let me know if I have to make any changes.

**Comment by akhikolla** [comment]
Hello @tdhock,

Passing logfile to user_error_display function gives the following output.
https://github.com/akhikolla/RcppDeepState/blob/update-analyze-and-display-errors/R/errorrcode.R 
 
Will this be enough or should I make any changes to the regex?
![image](https://user-images.githubusercontent.com/31878891/84838607-b7910300-afef-11ea-867a-b070dde7ae8b.png)

**Comment by tdhock** [comment]
maybe we need the pid e.g. ==1234== in order to match the errors with the input/binary/crash files?

**Comment by tdhock** [comment]
instead of just the file name/line numbers it would be better to also have the reason why each line number appears e.g. 
```
Invalid read of size 4, use_after_free.cpp:7
Address 0x59e43068 is 40 bytes inside a block of size 3,414,537,816 free'd, use_after_free.cpp:6
Block was alloc'd at, use_after_free.cpp:5
```

**Comment by akhikolla** [comment]
Sure @tdhock I'll try to get the unique ids along with the detailed error messages.

**Comment by tdhock** [comment]
by the way, can you explain how you plan to match up the log file messages with the input/binary/crash files? Does the pid method work? (is the pid of each input/binary/crash file known?) is there another method?

**Comment by akhikolla** [comment]
No @tdhock we don't have pid's for the binary crash files all we get from parsing a binary crash file are the inputs that are passed on to the executable.
Maybe we can match those inputs we get from binary file with the logfile parsed data table inputs column and get a pid for that input. 
But this fails when we have same inputs but different pid's in the logfile parsed data table.

**Comment by tdhock** [comment]
hey @agroce can you recommend a way forward here?
DeepState produces a binary crash file for each set of inputs that cause a test failure/crash, right?
Running the DeepState test harness under valgrind also produces output/log files like this https://github.com/akhikolla/RcppDeepState/blob/ec3ffa740881adc21209d978c9065271e2b47ef9/tests/testthat/use_after_free_log (containing memory error messages).
We would like some way to match error messages with input/binary/crash files, so the user can see which inputs caused which error messages. Does that make sense? How would you do that? 

I see that valgrind outputs a different ==pid== for each input, so we could do that matching using pid if there is some way to get the pid from DeepState input/binary/crash files?

We could write/generate some code in the test harness which creates a pid-specific directory for each set of generated inputs.

**Comment by agroce** [comment]
Hmm.  One really simple approach would be just to use the initial valgrind to catch failures, but then basically throw those away (delete the log files).  Then rerun in a script each crashing binary input, using --input_test_case <file> and store the resulting valgrind log + test case in a directory?  That way you don't have to worry about matching <pid>s and doing process management, plus it's a bit cleaner for memory errors anyway.  DeepState forking could cause annoyance with pid-based approaches anyway.

**Comment by tdhock** [comment]
that makes sense. anyway we were re-running the binary inputs using --input_test_case in order to get a human readable representation of the inputs, so it should not introduce any extra computation time.

**Comment by akhikolla** [comment]
Hello @tdhock,
Does the data table generated seem good with id, line number, and the reason for the error at that line?
Code looks like:

```
user_error_display<-function(logfile){
  error.dt <- nc::capture_all_str(
    logfile,
    arg.name=".*?",
    " values:",
    value=".*",
    "\n",
    id="==[0-9]+==",
    errortrace="(?:.*\n)*?", 
    "==[0-9]+== HEAP SUMMARY:",
    "\n",
    heapsum="(?:.*\n)*?",
    "==[0-9]+== LEAK SUMMARY:",
    "\n",
    leaksum="(?:.*\n)*?",
    "==[0-9]+== ERROR SUMMARY:")
  
  files.list<-nc::capture_all_str(logfile,"Command: ./",file.name=".*","_DeepState_TestHarness --fuzz")
  error.dt[, error.i := 1:.N]
  error.dt[,src.file.lines := {
    file.line.dt <- nc::capture_all_str(
      error.dt$errortrace,
      "==[0-9]+==",
       error=".*?","\n",
       line=".*?",
       file.line="[^()]+?:[0-9]+")
    file.line.dt[grepl(paste0(files.list$file.name,".cpp"), file.line),paste(error,file.line, collapse="\n"),]
  }, by=error.i]
  trace <- gsub("==[0-9]+== Warning:.*?\\n","",error.dt$errortrace)
  error.msg <- nc::capture_first_vec(trace,
                                     msg=".*")
  count.dt <- error.dt[, .(
    count=.N
  ), by=.(id,arg.name,value,src.file.lines,error.message=gsub("==[0-9]+==","",error.msg$msg))]
  
  return(count.dt)
}

```
![image](https://user-images.githubusercontent.com/31878891/85358233-1232cf00-b4c8-11ea-9cb0-a0cf6e7944fc.png)

But in the src.file.lines column the reason and line number appear twice how can I get it displayed only once? can you please suggest?

Thanks

**Comment by tdhock** [comment]
i don't think you need the pid anymore if we are going to use the method that Alex suggested above (first run generates the binary/input/crash files, then second run on each binary/input/crash file to get details about inputs/errors/line numbers).
Like I said before, it will be good to give the user the option to view the entire log file with full details, but it would also be good if you could display the problems/reasons which involve the user's Rpkg/src/*.cpp files. You could do that with grep?

**Comment by akhikolla** [comment]
Hello @tdhock 

As we discussed the user_error_data() function should return zero rows when there are no errors but it gives me an incorrect error trace. 
I am using this code: 
```
user_error_display<-function(logfile){
  error.dt <- nc::capture_all_str(
    logfile,
    arg.name=".*",
    " values: ",
    value=".*",
    "\n",
    errortrace="(?:.*\n)*?", 
    "==[0-9]+== HEAP SUMMARY:",
    "\n"),
    heapsum="(?:.*\n)*?",
    "==[0-9]+== LEAK SUMMARY:",
    "\n",
    leaksum="(?:.*\n)*?",
    "==[0-9]+== ERROR SUMMARY:")
  files.list<-nc::capture_all_str(logfile,"Command: ./",
                                  file.name=".*",
                                  "_DeepState_TestHarness --fuzz")
  error.dt[, error.i := 1:.N]
  error.dt[, src.file.lines := {
    file.line.dt <- nc::capture_all_str(
      error.dt$errortrace,
      file.line="[^()]+?:[0-9]+")
    file.line.dt[grepl(paste0(files.list$file.name,".cpp"), file.line),paste(file.line, collapse="\n")]
  }, by=error.i]
  trace <- gsub("==[0-9]+== Warning:.*?\\n","",error.dt$errortrace)
  error.msg <- nc::capture_first_vec(trace,
                                     msg=".*")
  #error.msg <- nc::capture_first_vec(error.dt$errortrace,"\n",
  #                                  err.msg=".*")
  count.dt <- error.dt[, .(
    count=.N
  ), by=.(arg.name,value,src.file.lines=gsub(" ",""src.file.lines),error.message=gsub("==[0-9]+==","",error.msg$msg))]
  
  return(count.dt)
}


```

error.dt is not parsing all the inputs although they have a pattern with `values:`  separated. I don't understand why inputs are getting read as errortrace message.
arg.name is not giving all the parameters and its values as in 
 arg.name
 1:          input_data
 2:   input_label_start
 3:     input_label_end
 4: input_label_changes
 5:           n_updates
 6:   penalty_unlabeled
It is not even taking the inputs into the values field but all of these inputs are going into the error message field
     arg.name
1: input_data
2: input_data
3: input_data
4: input_data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             value
1:                                                                                                                                                                                                                                                               -6.06735e+277 4.21415e-181 -7.91917e-125 -1.31707e+58 -2.26834e-48 -6.86014e-108 9.73068e-47 4.40674e+170 -1.26011e+123 6.99286e+87 -1.14818e+300 -5.35943e+198 6.28612e-112 -5.35524e-213 9.6068e-231 -8.20988e+138 -2.72232e+260 5.41324e-121 -1.25096e-141 1.20183e+81 1.25821e+79 1.81358e+306 -2.80477e-182 -0.000588061 2.00846e+229 4.92775e-159 4.21946e+87 -1.35186e+65 1.753e+236 2.73319e+28 8.4502e-22 1.19914e+93 -7.27581e-104 -7.11022e+144 3.01266e+41 -7.3841e+140 -3.68604e-242 2.01963e-70 -6.00694e-24 5.99327e-134 -2.25357e-119 1.39695e-299 -3.68454e+261 1.0803e+245 7.79151e+270 5.80133e+197 -1.9433e-179 -1.91594e-72 -4.46057e+100 5.66764e+271 7.38796e+202 -7.07572e-213 3.41054e+81 6.52507e-110 1.14103e-160 7.40163e-203 9.6224e+207 -1.34835e+151 -6.02965e-203 -7.3283e+26 1.41572e-05 -7.74916e-78 -2.2159e-131 -3.38494e-222 3.32467e+24 -3.02161e+26 1.38959e-154 -1.28509e+96 3.13225e-182 9.50655e-102 1.10768e+134 2.00197e-207 2.74977e+75 -1.11522e+279 3.40905e+248 0
2:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2.40205e+90 -1.22526e-252 9.056e-39 9.38406e-48 1.40613e+266 3.54769e+19 0
3: 5.8097e+170 4.22754e+202 -4.64369e-82 -3.25243e-199 4.72981e+82 2.216e-200 -6.35948 2.1136e-75 -1.27153e-166 4.31515e+16 -1.83189e+19 1.3214e-114 -2.59004e-65 6.30648e+233 1.44873e+208 -5.65245e+57 -2.1501e-280 1.38996e+218 -2.654e+37 1.07762e-268 -5.80052e-129 -5.51486e-190 9.4458e-137 2.49447e+216 6.52743e-170 1.50175e+190 -1.63609e-106 3.58789e+305 -6.71668e-55 6.47549e+173 -1.33827e-184 3.04006e-285 -1.80268e-56 3.43888e-233 -1.37739e+191 -8.45045e-151 -2.93712e+252 -2.17122e-104 -2.71926e-136 -2.40334e+102 -3.49496e-144 1.05123e-235 -1.08095e-192 6.55776e-93 -1.48347e-209 -6.64111e+198 -1.0281e-102 2.01038e-170 2.22427e+257 -4.06349e-106 -1.20255e-55 3.55867e+33 -7.88979e+14 2.60051e+227 1.37589e-222 1.11697e-275 9.44175e-92 3.87252e-14 7.30987e+11 -9.3982e-66 -5.31205e+183 1.12962e+68 8.16751e-156 -1.27876e+82 -3.11585e+171 4.9781e-172 5.37278e+82 -1.41742e-188 -1.7111e+286 1.36538e-188 -1.36993e-25 2.59859e+265 -1.35574e+250 -1.64885e-08 2.0641e+235 -5.75251e+138 2.1676e+126 -1.76692e+133 1.81535e-191 8.19165e+65 -2.23143e-298 -1.72856e+174 4.62394e-219 -3.18001e+172 -1.06805e-239 1.96703e+159 8.88308e-26 -6.49196e+122 2.18011e+208 -4.39613e+104 1.35431e+301 0.04781 -1.16785e+231 2.16068e+52 4.62147e+62 0
4:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     4.85528e-84 -3.04853e+203 -3.39539e+282 -9.28451e-157 1.98471e-291 -9.35513e+275 3.30265e+60 4.90413e+222 3.57832e-131 -3.87774e-247 6.27689e-290 6.25683e-96 -4.02839e+223 -6.15245e+249 -4.75844e+121 -1.94403e-247 6.53791e-164 1.4584e+185 4.6616e+06 4.46804e+171 4.4212e+163 3.56543e+260 -1.22792e+230 2.63357e-57 0
   src.file.lines
1:               
2:               
3:               
4:               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         error.message
1:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         input_label_start values: -962013874 1223085193 929356059 -698822509 -844067786 321479415 -1981125895 537901542 -1215417089 1946192299 1684194875 -1164456313 1197129050 -2095034100 180028714 -893513342 1279623617 1175088298 1815340327 -894194159 225209232 -1933796202 2007089474 1607648428 390425949 1356400828 216916950 -1584207954 -28164214 249241734 2111949020
2:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                input_label_start values: 534434348 1217769798 64847086 -2143564543 -1375766326 2040217066 1614491102 -1291814701 -632619229 -525243933 -1897541362 564072398 -1635280873 601162115 271540676 802789129 613821444 1201006549 2075714716 1475570421 2063731870 -670162456 1032039532 1547924864 -626883551 929822642 618352251 -826773175 -1149376621 -1962312760 -1943522072 1806330181 1290626947 1499346557 965015559 1030312440 -415724686 1090927565 779073178 421519205 205973861 -1541414179 -1545869856 1144444971 1852022448 1792638360 1211314786 1376962399 1487979773 -811083149 -2101390394 -181603740 -1886382855 1771147953 -977005801
3: input_label_start values: 2009327628 332040540 -579777555 -528292648 1638933451 -89702787 -1607415109 753231011 -1454592068 389552628 -1453006454 -423206329 1988432753 760344269 -2118612818 -1628679865 956367696 958153955 -2128253593 -338710686 1438831490 331435925 2060993304 -996909059 -1788719665 2140254720 -1222678622 -300547005 -656947732 -1726643949 -305910863 1485484014 -318980757 -1905300667 -1898715268 -370360126 -1014649252 -1708167289 -207996597 619198737 -453608334 1709750259 -1147178844 -1959762354 -1256936624 1125832502 -1257209127 -121902371 -1301852393 1325861642 -1501843919 -1424654496 690663533 1166582778 -1742351471 -507613549 633186932 -994738582 808229851 1092303979 1173149834 1954251789 -1588027774 369890619 -910184562 1965947045 1502904731 -1346566412 -1445036258 1493380090 1539931249 -711873378 1364929734 -2010813470 -1175683736 -1451008941 1641771450 -543378118 1697754170 -1017587692 -1274684868 709172963 849038299 514272895 -2086716830 1005558944 541645539 -1582041259 -1194225182 397460809 1259349098 -1219237574 -232547282 305778227 -2119625182 1544451860 -552995082
4:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                input_label_start values: 1155969181 746536347 -1354493494 -503366329 1072772709 1881879149 -1302158962 362798425 -2037516622 204754619 2019525978 1606590878 -1260977372 53907893 -1741470546 -769587368 -1342305349 844724138 -1191443433 -1079659149 2109314944 -282577529 1534670126 -1690466742
   count
1:     1
2:     1
3:     1
4:     1

In these listed log files patterns are different in each log file. Can you help me know where exactly is my code going wrong in detecting the error trace?
How can I get the no_error_logfile.txt to return zero rows using the above code?
[heap_errorlogfile.txt](https://github.com/akhikolla/RcppDeepState/files/4843071/heap_errorlogfile.txt)
[stack_trace_logfile.txt](https://github.com/akhikolla/RcppDeepState/files/4843072/stack_trace_logfile.txt)
[no_error_logfile.txt](https://github.com/akhikolla/RcppDeepState/files/4843073/no_error_logfile.txt)

**Comment by tdhock** [comment]
hi please reformat your issue comments using triple backticks ``` for code/result blocks (much easier to read)
```
like this
```

**Comment by akhikolla** [comment]
Sure @tdhock. I updated the comment

**Comment by tdhock** [comment]
I'm not sure, I think you need to do some debugging.
