### ISSUE TITLE
Note for object files 

### ISSUE THREAD

**Issue by akhikolla** [akhikolla/RcppDeepState#12]
Hello @tdhock 

Even Makevars to generate deepstate library and object files for test packages doesn't clear the note. I still get this saying:
* checking if this is a source package ... NOTE
Found the following apparent object files/libraries:
  inst/lib/libdeepstate.a
  inst/testpkgs/binsegRcpp/src/binseg_normal_cost.o
  inst/testpkgs/binsegRcpp/src/binseg_normal.o
  inst/testpkgs/binsegRcpp/src/rcpp_interface.o
  inst/testpkgs/binsegRcpp/src/RcppExports.o
  inst/testpkgs/testSAN/src/RcppExports.o
  inst/testpkgs/testSAN/src/read_out_of_bound.o
  inst/testpkgs/testSAN/src/use_after_deallocate.o
  inst/testpkgs/testSAN/src/use_after_free.o
  inst/testpkgs/testSAN/src/write_index_outofbound.o
  inst/testpkgs/testSAN/src/zero_sized_array.o

Code in Makevars to get the objects for *.cpp files in testpkgs

SOURCES_TEST=../inst/testpkgs/binsegRcpp/src/RcppExports.cpp ../inst/testpkgs/binsegRcpp/src/binseg_normal.cpp ../inst/testpkgs/binsegRcpp/src/binseg_normal_cost.cpp ../inst/testpkgs/binsegRcpp/src/rcpp_interface.cpp ../inst/testpkgs/testSAN/src/RcppExports.cpp ../inst/testpkgs/testSAN/src/read_out_of_bound.cpp ../inst/testpkgs/testSAN/src/use_after_deallocate.cpp ../inst/testpkgs/testSAN/src/use_after_free.cpp ../inst/testpkgs/testSAN/src/write_index_outofbound.cpp ../inst/testpkgs/testSAN/src/zero_sized_array.cpp
OBJECTS_TEST = $(SOURCES_TEST:.cpp=.o)
$(SHLIB): $(OBJECTS_TEST)

Please let me know how to proceed with this.
Thanks

**Comment by tdhock** [comment]
first of all it is good that you don't have any of those object files in your git repo. (there must only be source files, not any object files, included in R packages)

do those object files exist in your source package (before you do R CMD build) ? If so why are they there? If you are compiling them during tests you should do that in a different directory, probably under tempdir() / tempfile()

you should remove any object files before calling R CMD build. 
Rpkg/inst/* items in the source pkg are copied verbatim to the installed Rpkg directory (including any object files that you may have in there).

**Comment by akhikolla** [comment]
Generating the object files during the R CMD check and note is no longer seen
