### ISSUE TITLE
 issue with disk space issue

### ISSUE THREAD

**Issue by akhikolla** [akhikolla/RcppDeepState#13]
Hello @tdhock,

When I check my RcppDeepState package I get this note.
* checking installed package size ... NOTE
  installed size is  6.1Mb
  sub-directories of 1Mb or more:
    testpkgs   5.7Mb
Although my testpkgs has only 2 subfolders and corresponding src/*.cpp files.
Is there a way that I can get rid of this note?

**Comment by tdhock** [comment]
RcppDeepState/inst/testpkgs is copied verbatim to RcppDeepState/testpkgs so you need to delete whatever files in there are taking up that space. the source code takes 68kb so if you remove everything else then that NOTE should go away
```
(base) tdhock@maude-MacBookPro:~/R/RcppDeepState$ du -k inst/testpkgs/
28	inst/testpkgs/binsegRcpp/src
32	inst/testpkgs/binsegRcpp
28	inst/testpkgs/testSAN/src
32	inst/testpkgs/testSAN
68	inst/testpkgs/
```

**Comment by akhikolla** [comment]
Sure @tdhock I'll do that. Thanks for the suggestion
