### ISSUE TITLE
deepstate_pkg_create message

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#17]
I see
```
> RcppDeepState::deepstate_pkg_create("~/R/LOPART")
[1] "Testharness created!!"
```
maybe user would like to know what files were created?

**Comment by akhikolla** [comment]
Sure @tdhock I will display the list of testharness files and their respective makefiles in that source location.

**Comment by tdhock** [comment]
for those kind of messages you should probably use `message` rather than returning a character string. (maybe return nothing/NULL?)

**Comment by akhikolla** [comment]
returning the values considering the datatypes of the functions.
