### ISSUE TITLE
remove git requirement for make_run

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#19]
currently it has
```
  system(paste0("cd ",insts.path, " ; ", "git clone https://github.com/trailofbits/deepstate.git"))
```
which means the user must have git. That is probably true, but it would be more portable to avoid that assumption, and just use 
```r
insts.path <- "~"
deepstate.zip <- file.path(insts.path, "deepstate-master.zip")
download.file("https://github.com/trailofbits/deepstate/archive/master.zip", deepstate.zip)
unzip(deepstate.zip, exdir=insts.path)
```

That gives me
```
> dir("~/deepstate-master")
 [1] "bin"            "CMakeLists.txt" "docker"         "docs"          
 [5] "examples"       "extras"         "LICENSE"        "mypy.ini"      
 [9] "push"           "README.md"      "src"            "tests"         
[13] "Vagrantfile"   
```

**Comment by akhikolla** [comment]
Okay, @tdhock you want deepstate to be installed in the root directory of the user and download the git repo instead of cloning it.
I'll get that done.

**Comment by tdhock** [comment]
well maybe not installed in the root of the user home directory, maybe in ~/.RcppDeepState ?? (that will be invisible)

**Comment by akhikolla** [comment]
@tdhock isn't that ~/.R which gets ignored by the package build? Will ~/.RcppDeepState work the same as ~/.R?
If so should I create the ~/.RcppDeepState first or it already exists?

**Comment by tdhock** [comment]
I don't understand what you mean about " ~/.R which gets ignored by the package build" -- what is ~/.R?
Typically I think neither ~/.R nor ~/.RcppDeepState would exist (there are none on my system, are there on yours?) so you would have to create that (dir.create).
I have a lot of other ~/.something directories though, where something is one of: emacs.d, emacspeak, gconf, gnupg, keras, mozilla, scribus, ssh, subversion, etc

**Comment by akhikolla** [comment]
@tdhock ~/.R is where we usually store the Makevars.
We can use this Makevars to compile and create a static library in ~/.R instead of a call to the make_run()(where we create the static library in inst folder). I guess using this Makevars we can enable the use of deepstate static library on every package (just like we specify library paths, flags in Makevars which are enabled on all the packages).  
If this is not possible then I can create ~/.RcppDeepState folder and generate the library in here by making a call to make_run.
Even I don't have  ~/.R and ~/.RcppDeepState in my system, I need to create them.

**Comment by tdhock** [comment]
you are right, I forgot about ~/.R/Makevars, but that is used by R for package installation/compilation, whereas we are doing test harness compilation, which is quite different, so I don't think we should use that.
You may want to compile the deepstate static library under ~/.R/deepstate or ~/.R/RcppDeepState/deepstate, anything is fine (under user home directory so we know that it is writeable).

**Comment by akhikolla** [comment]
using download.file() for the specified URL throws Valgrind vex errors. So installing the package using wget.
Also installing the static library under ~/.R/RcppDeepState/deepstate/build as discussed and it works without any errors.
