### ISSUE TITLE
remove deepstate_create_testpkgs_objects() from tests?

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#25]
compiling package functions to object files should happen in one of your deepstate_* functinos.

**Comment by tdhock** [comment]
same thing for deepstate_make_run() ? (only run if needed)

**Comment by tdhock** [comment]
if file exists ( package/src/package.so )
if file exists ( ~/.RcppDeepState/static.library. )

**Comment by akhikolla** [comment]
To compiling package functions to object files -- installing the package inside deepstate_pkg_create()

`
system(paste0("R CMD INSTALL ",package_path))
`

Checking for the static library if it doesn't exist - creates one
```
  if(!file.exists("~/.RcppDeepState/deepstate-master/build/libdeepstate.a")){
        deepstate_make_run()     //creates the library 
}
```
