### ISSUE TITLE
sub-directory for every function?

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#28]
Right now all functions are saved in inst/testfiles/ can we make function-specific sub-directories instead? e.g. for binsegRcpp
inst/testfiles/binseg_normal
inst/testfiles/binseg_normal_cost
and then put all the files specific to that function under the corresponding sub-directory

**Comment by tdhock** [comment]
with this new structure you can use inst/testfiles/binseg_normal/Makefile instead of inst/testfiles/binseg_normal.Makefile (so then you can run make without the -f flag)

**Comment by tdhock** [comment]
also I would suggest putting input argument data files under a sub-directory, e.g.
```
inst/testfiles/binseg_normal/inputs/data_vec
inst/testfiles/binseg_normal/inputs/max_segments
```

**Comment by akhikolla** [comment]
Implemented the same structure - function specific folders and inputs in the sub folders.

**Comment by akhikolla** [comment]
function-specific harness and Makefile in - function folder
inputs - function folder/inputs
outputs(for binary files) - functionfolder/function_output
