### ISSUE TITLE
tests?

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#3]
hi @akhikolla please create a tests/testthat/test-write-to-bad-memory.R etc with tests using simple buggy Rcpp functions.

**Comment by akhikolla** [comment]
Hello @tdhock 
New branch having the tests to the functions,(tests on analyzing the log files for the functions)
https://github.com/akhikolla/RcppDeepState/tree/update-analyze-and-display-errors

**Comment by tdhock** [comment]
ok then please open a PR

**Comment by akhikolla** [comment]
@tdhock Here is the pull request https://github.com/akhikolla/RcppDeepState/pull/5
But Travis checks are getting failed. In the local machine, the tests seem to work fine

**Comment by akhikolla** [comment]
Travis checks are successful. Deepstate runs the executables without any failures.

**Comment by tdhock** [comment]
great! what are the tests checking for?

**Comment by akhikolla** [comment]
It checks for DeepState Testharness files and corresponding makefiles existence and their respective log files and binary output folders with the *.crash, *.fail files, and in log files, it also checks for argument names, line numbers and source file lines and error messages.
