### ISSUE TITLE
incorrect report of successful compilation

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#30]
Hi @akhikolla if I run deepstate_harness_compile_run without first creating the test harness/makefiles I get the following incorrect report of sucess:
```
> RcppDeepState::deepstate_harness_compile_run("~/R/binsegRcpp")
[1] "rm -f *.o && make -f ~/R/binsegRcpp/inst/testfiles/read_memory.Makefile "
make: /home/tdhock/R/binsegRcpp/inst/testfiles/read_memory.Makefile: No such file or directory
make: *** No rule to make target '/home/tdhock/R/binsegRcpp/inst/testfiles/read_memory.Makefile'.  Stop.
[1] "rm -f *.o && make -f ~/R/binsegRcpp/inst/testfiles/read_new.Makefile "
make: /home/tdhock/R/binsegRcpp/inst/testfiles/read_new.Makefile: No such file or directory
make: *** No rule to make target '/home/tdhock/R/binsegRcpp/inst/testfiles/read_new.Makefile'.  Stop.
[1] "rm -f *.o && make -f ~/R/binsegRcpp/inst/testfiles/read_malloc.Makefile "
make: /home/tdhock/R/binsegRcpp/inst/testfiles/read_malloc.Makefile: No such file or directory
make: *** No rule to make target '/home/tdhock/R/binsegRcpp/inst/testfiles/read_malloc.Makefile'.  Stop.
[1] "rm -f *.o && make -f ~/R/binsegRcpp/inst/testfiles/binseg_normal.Makefile "
make: /home/tdhock/R/binsegRcpp/inst/testfiles/binseg_normal.Makefile: No such file or directory
make: *** No rule to make target '/home/tdhock/R/binsegRcpp/inst/testfiles/binseg_normal.Makefile'.  Stop.
[1] "rm -f *.o && make -f ~/R/binsegRcpp/inst/testfiles/binseg_normal_cost.Makefile "
make: /home/tdhock/R/binsegRcpp/inst/testfiles/binseg_normal_cost.Makefile: No such file or directory
make: *** No rule to make target '/home/tdhock/R/binsegRcpp/inst/testfiles/binseg_normal_cost.Makefile'.  Stop.
[1] "Compiled all the functions in the package successfully"
> 
```
Maybe add a test for this case?
Or combine the test harness creation + compilation in the same function so you don't have to worry about a user who runs the compilation without having first created the test harness files?

**Comment by akhikolla** [comment]
Sure @tdhock I can combine the creation and compilation steps. Also, the user wouldn't want to keep calling all the methods(create, compile, error display) it would be good if he can call a single function and get his work done.

**Comment by akhikolla** [comment]
checking for the existence of the testharness file and corresponding makefile before compiling the testharness.
 we get the following when we run deepstate_harness_compile_run() without first creating the test harness/makefiles

```
> dhcr <- deepstate_harness_compile_run("~/R/binsegRcpp") 
TestHarness and makefile doesn't exist for - rcpp_binseg_normal
TestHarness and makefile doesn't exist for - rcpp_binseg_normal_cost
```

**Comment by tdhock** [comment]
ok that is definitely better.
if this is a user-visible (exported) function then please add an error with a message that tells how to fix the problem (use deepstate_pkg_create first).
otherwise if it is not exported that is fine to keep as is.
