### ISSUE TITLE
run compileAttributes before parsing RcppExports.cpp

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#33]
Hi @akhikolla in the current code of deepstate_pkg_create you assume the RcppExports.cpp file is already up to date, but maybe it is not. In fact it is not in your current testpkgs. Please run Rcpp::compileAttributes in deepstate_pkg_create, before you parse the RcppExports.cpp file, so you know it is up to date.
Also I think you need to add a DESCRIPTION to testpkgs for Rcpp::compileAttributes to work. Right now I get an error:
```
> Rcpp::compileAttributes("~/R/RcppDeepState/inst/testpkgs/testSAN")
Error in Rcpp::compileAttributes("~/R/RcppDeepState/inst/testpkgs/testSAN") : 
  pkgdir must refer to the directory containing an R package
> 
```

**Comment by akhikolla** [comment]
Added the Description and Namespace files to the package and running Rcpp::compileAttributes(path) in the deepstate_pkg_create function and it doesn't throw any error now.

```
> Rcpp::compileAttributes("~/R/RcppDeepState/inst/testpkgs/testSAN")
>
```

**Comment by tdhock** [comment]
great
