### ISSUE TITLE
input parsing plan?

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#38]
the initial plan for reading each randomly generated input from a text file seems a bit simpler than your current plan, which entails parsing the values from the log file, right?
@akhikolla what is your plan on how to do that for more complex types like NumericMatrix?

**Comment by akhikolla** [comment]
I found that it will be easier to read inputs and corresponding errors from the log file for specific binary input than to read the inputs separately from the text files.

For now, I am just reading the values from the log file like this: 

Here mat is a NumericMatrix, the remaining arguments are of type int, double
```
mat values: -1.55541e+232 5.35293e-177 -9.19494e+195 2.24775e+307
8.85319e-58 7.48310e+261 2.63356e+221 6.04022e-69
-6.17757e-156 1.17261e+120 -6.89845e-292 -7.97386e+81
2.21124e-110 -4.01481e+15 -1.66794e+147 -2.71927e-203

N values: -1253872166
w0 values: 2.79647e-296
k values: -3268.39
eps values: 9.03194e-44


```

**Comment by tdhock** [comment]
print data type to log file?

**Comment by tdhock** [comment]
how to get dimensions of matrix?

**Comment by tdhock** [comment]
maybe easier to call saveRDS on each input? from https://stackoverflow.com/questions/10954077/write-an-rdata-file-from-c 
```cpp
using namespace Rcpp;
Environment base("package:base");
Function saveRDS = base["saveRDS"];
NumericMatrix xx(wrap(M));
saveRDS(xx,Named("file","Identity.RDs"));
```

**Comment by akhikolla** [comment]
Using saveRDS and readRDS throws error in the testharness:

1. Tried using saveRDS and read RDS in testharness and also tried creating a new CPP function in RcppDeepState/inst/extdata to perform the same saveRDS and readRDS and linked it to the testharness and made a call to that function we get the following error:
```
using namespace Rcpp;

TEST(deepstate_test,datatype){
std::ofstream value_stream;
RInside();
Rcpp::NumericMatrix mat = RcppDeepState_NumericMatrix();
Environment base("package:base");
Function saveRDS = base["saveRDS"];
Function readRDS = base["readRDS"];
saveRDS(mat,Named("file","mat.RDs"));
readRDS("mat.RDs");
}
```
![image](https://user-images.githubusercontent.com/31878891/92020471-04da6200-ed0d-11ea-83a7-9a7393ec23d7.png)


2. Created a .RDS file instead of a text file to save each input and tried to read it using readRDS - it says the input file has invalid input format.

`value_stream.open("~/R/RcppDeepState/mat.RDs");`

```
 > readRDS("mat.RDS")
Error in readRDS("mat.RDS") : unknown input format
```
3.Tried using save() and load() and changed the file format to RData instead of RDs

```
> load("~/R/RcppDeepState/data.RData")
Error in load("~/R/RcppDeepState/data.RData") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘data.RData’ has magic number '1  2 '
  Use of save versions prior to 2 is deprecated
```

**Comment by tdhock** [comment]
two types of file formats: RData format (save/load) DO NOT USE HERE.
rds format: (readRDS/saveRDS) USE HERE.

**Comment by tdhock** [comment]
what is the difference between the code that works and the code that does NOT?

**Comment by akhikolla** [comment]
```
void callFunction(Rcpp::NumericVector mat) {
  Environment base("package:base");
  Function saveRDS = base["saveRDS"];
  saveRDS(mat,Named("file","mat.RDs"));
  Function readRDS = base["readRDS"];
   readRDS("mat.RDs");
  }

```

**Comment by tdhock** [comment]
#48 explains that qs can be used for saving randomly generated inputs to disk, and then reading them later so that the R user can see what values crashed their function.
