### ISSUE TITLE
why --fuzz_save_passing?

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#47]
that argument is used when running the test harness binary, but don't we only care about test failures? why do we need to save the binary/input files when the tests pass?

**Comment by akhikolla** [comment]
Using `--fuzz_save_passing` saves all passing, failing, and crashing inputs.
I just wanted to save all the binary inputs passed on to the function. We can remove the --fuzz_save_passing
and just add the code below to save only the failing and crashing inputs.

```
./<exec>--fuzz --output_test_dir <output_folder>
```

**Comment by akhikolla** [comment]
Removed argument --fuzz_save_passing and saving only the failing and crashing inputs

**Comment by tdhock** [comment]
ok
