### ISSUE TITLE
analyze_one returns NULL

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#53]
This is after having already run compile_run -- I was expecting a summary table with inputs that caused problems. Am I using it incorrectly? If so can you please stop with an error instead of returning NULL?
```
> (result <- RcppDeepState::deepstate_harness_analyze_one("/home/tdhock/R/RcppExports/packages/bnnSurvival/inst/testfiles/weighted_kaplan_meier"))
NULL
```

**Comment by akhikolla** [comment]
This function doesn't return any value. `RcppDeepState::deepstate_harness_analyze_one("/home/tdhock/R/RcppExports/packages/bnnSurvival/inst/testfiles/weighted_kaplan_meier"))` it will print the datatable if there are any errors.

**Comment by tdhock** [comment]
can you return the data table instead of printing it? (in this case a 0 row data table would indicate no issues found)
printing should be avoided in general.

**Comment by akhikolla** [comment]
Sure I'll return a data table.

**Comment by tdhock** [comment]
hi this still seems to be an issue,
```
> RcppDeepState::deepstate_harness_analyze_one("/home/tdhock/R/RcppExports/packages/BNSL/inst/testfiles/mi")
> RcppDeepState::deepstate_harness_analyze_one("/home/tdhock/R/RcppExports/packages/BNSL")
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
character(0)
```
maybe change the name from analyze_one to analyze_pkg?
also would be useful to have a function analyze_fun, e.g.
```
RcppDeepState::deepstate_harness_analyze_fun("/home/tdhock/R/RcppExports/packages/BNSL/inst/testfiles/mi")
RcppDeepState::deepstate_harness_analyze_pkg("/home/tdhock/R/RcppExports/packages/BNSL")
```

**Comment by tdhock** [comment]
also should stop with an error if you use it on the wrong directory, 
```
> RcppDeepState::deepstate_harness_analyze_pkg("/home/tdhock/R/RcppExports/packages/BNSL/inst/testfiles/mi")
Error; /home/tdhock/R/RcppExports/packages/BNSL/inst/testfiles/mi is not a package directory
> RcppDeepState::deepstate_harness_analyze_pkg("/home/tdhock/R/RcppExports/packages/BNSL")
Error: /home/tdhock/R/RcppExports/packages/BNSL is not a package/inst/testfiles/function directory
```

**Comment by akhikolla** [comment]
> hi this still seems to be an issue,
> 
> ```
> > RcppDeepState::deepstate_harness_analyze_one("/home/tdhock/R/RcppExports/packages/BNSL/inst/testfiles/mi")
> > RcppDeepState::deepstate_harness_analyze_one("/home/tdhock/R/RcppExports/packages/BNSL")
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> character(0)
> ```
> 
Did you run compile_run before running analyze one?

> maybe change the name from analyze_one to analyze_pkg?
> also would be useful to have a function analyze_fun, e.g.
> 
> ```
> RcppDeepState::deepstate_harness_analyze_fun("/home/tdhock/R/RcppExports/packages/BNSL/inst/testfiles/mi")
Yes we have a function like that. Please use deepstate_analyze_one(fun_path) to test a function.

And I'll change the function names as suggested.

**Comment by tdhock** [comment]
yes I did run compile_run first.
would be even better if you could programmatically check whether or not compile_run has already been done, and stop with an error if not.

**Comment by akhikolla** [comment]
Making a call to analyze one inside the compile run functionon and specifying the max number of files to analyze.

**Comment by tdhock** [comment]
is this resolved?

**Comment by akhikolla** [comment]
Yes, the issue is resolved the analyze_pkg function returns a data table with crash files, inputs, and datatable with issues for all the functions in the package. 
If there are no binary files for a function then it gives a message - No bin files exist for function <function name>.

```
> rd <- deepstate_harness_analyze_pkg("~/R/x86_64-pc-linux-gnu-library/3.6/RcppDeepState/testpkgs/testSAN")
Read 1 item
Read 1 item
Read 1 item
No bin files exists for function rcpp_use_after_deallocate

No bin files exists for function rcpp_use_after_free

No bin files exists for function rcpp_use_uninitialized

Read 1 item
Read 1 item
Read 1 item
No bin files exists for function rcpp_zero_sized_array
> rd
                                                                                                                                                                                                   binaryfile
1:            /home/akolla/R/x86_64-pc-linux-gnu-library/3.6/RcppDeepState/testpkgs/testSAN/inst/testfiles/rcpp_read_out_of_bound/rcpp_read_out_of_bound_output/13dede81d4526baf7caab29b9ff488e9bb78afa7.pass
2:            /home/akolla/R/x86_64-pc-linux-gnu-library/3.6/RcppDeepState/testpkgs/testSAN/inst/testfiles/rcpp_read_out_of_bound/rcpp_read_out_of_bound_output/1f9462aa87c5612c3413caf941e9540639a9b434.pass
3:            /home/akolla/R/x86_64-pc-linux-gnu-library/3.6/RcppDeepState/testpkgs/testSAN/inst/testfiles/rcpp_read_out_of_bound/rcpp_read_out_of_bound_output/33e69d498cc84987375401f6333de792a7844cdc.pass
4: /home/akolla/R/x86_64-pc-linux-gnu-library/3.6/RcppDeepState/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_output/544fee2e3a7c980c7d93aca9f779151795673856.crash
5: /home/akolla/R/x86_64-pc-linux-gnu-library/3.6/RcppDeepState/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_output/66844ae02be1b952c76e99488b46d7c4d581f721.crash
6: /home/akolla/R/x86_64-pc-linux-gnu-library/3.6/RcppDeepState/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_output/8a22e8523c99574c1cf6b849770d602ea419c6b0.crash
      inputs          logtable
1: <list[1]> <data.table[2x5]>
2: <list[1]> <data.table[2x5]>
3: <list[1]> <data.table[2x5]>
4: <list[1]> <data.table[1x5]>
5: <list[1]> <data.table[1x5]>
6: <list[1]> <data.table[1x5]>
> 

```
