### ISSUE TITLE
Use \n at the end of cat?

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#55]
Hi @akhikolla I am running compile_run and I see
```
cd /home/tdhock/R/RcppExports/packages/bnnSurvival/inst/testfiles/weighted_kaplan_meier && rm -f *.o && makeclang++ -g -I/home/tdhock/lib/R/include -I/home/tdhock/R
```
note how there is no space/newline between make and clang++
I think this is because you are using cat() in R to display the command line that you are using with system, right? You should use \n at the end of each cat() so you get a newline.

**Comment by akhikolla** [comment]
Using \n to seperate the lines. Issue resolved
