### ISSUE TITLE
valgrind false positive suppression

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#6]
Brian Ripley suggests ignoring some false positives in valgrind output via the following valgrind suppression file: (put this into wcsrtombs.supp)
```
{
   Suppression for wcsrtombs
   Memcheck:Cond
   fun:__wcsnlen_sse4_1
   fun:wcsrtombs
   fun:wcstombs
}

{
   Suppression for do_makename
   Memcheck:Addr16
   fun:__wcsnlen_sse4_1
   fun:wcsrtombs
   fun:wcstombs
}
```
He says that the following is used on the valgrind command line options
```
--suppressions=/data/blackswan/ripley/wcsrtombs.supp
```
and the valgrind man page explains:
```
       --suppressions=<filename> [default: $PREFIX/lib/valgrind/default.supp]
           Specifies an extra file from which to read descriptions of errors
           to suppress. You may use up to 100 extra suppression files.
```
@akhikolla can you please add this suppression file option to the valgrind command line you are using?

**Comment by tdhock** [comment]
without this supp file I get the "conditional jump or move..." message false positive from valgrind:
```
(base) tdhock@maude-MacBookPro:~/projects/LOPART-paper$ R --vanilla -d valgrind -e 'extSoftVersion()'
==5569== Memcheck, a memory error detector
==5569== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==5569== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==5569== Command: /home/tdhock/lib/R/bin/exec/R --vanilla -e extSoftVersion()
==5569== 
==5569== Conditional jump or move depends on uninitialised value(s)
==5569==    at 0x55AC9E0: __wcsnlen_sse4_1 (strlen.S:147)
==5569==    by 0x5599EC1: wcsrtombs (wcsrtombs.c:104)
==5569==    by 0x551FB20: wcstombs (wcstombs.c:34)
==5569==    by 0x50BBD27: wcstombs (stdlib.h:154)
==5569==    by 0x50BBD27: tre_parse_bracket_items (tre-parse.c:336)
==5569==    by 0x50BBD27: tre_parse_bracket (tre-parse.c:453)
==5569==    by 0x50BBD27: tre_parse (tre-parse.c:1380)
==5569==    by 0x50B37B8: tre_compile (tre-compile.c:1920)
==5569==    by 0x50B0F00: tre_regcompb (regcomp.c:150)
==5569==    by 0x4FAA672: do_gsub (grep.c:2023)
==5569==    by 0x4F79775: bcEval (eval.c:7090)
==5569==    by 0x4F85E5F: Rf_eval (eval.c:723)
==5569==    by 0x4F87C7E: R_execClosure (eval.c:1888)
==5569==    by 0x4F88A46: Rf_applyClosure (eval.c:1814)
==5569==    by 0x4F86032: Rf_eval (eval.c:846)
==5569== 

R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> extSoftVersion()
                                             zlib 
                                         "1.2.11" 
                                            bzlib 
                             "1.0.6, 6-Sept-2010" 
                                               xz 
                                          "5.2.2" 
                                             PCRE 
                               "10.31 2018-02-12" 
                                              ICU 
                                           "60.2" 
                                              TRE 
                        "TRE 0.8.0 R_fixes (BSD)" 
                                            iconv 
                                     "glibc 2.27" 
                                         readline 
                                            "7.0" 
                                             BLAS 
"/usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1" 
> 
> 
==5569== 
==5569== HEAP SUMMARY:
==5569==     in use at exit: 40,492,984 bytes in 9,170 blocks
==5569==   total heap usage: 19,784 allocs, 10,614 frees, 62,951,480 bytes allocated
==5569== 
==5569== LEAK SUMMARY:
==5569==    definitely lost: 0 bytes in 0 blocks
==5569==    indirectly lost: 0 bytes in 0 blocks
==5569==      possibly lost: 0 bytes in 0 blocks
==5569==    still reachable: 40,492,984 bytes in 9,170 blocks
==5569==                       of which reachable via heuristic:
==5569==                         newarray           : 4,264 bytes in 1 blocks
==5569==         suppressed: 0 bytes in 0 blocks
==5569== Rerun with --leak-check=full to see details of leaked memory
==5569== 
==5569== For counts of detected and suppressed errors, rerun with: -v
==5569== Use --track-origins=yes to see where uninitialised values come from
==5569== ERROR SUMMARY: 46 errors from 1 contexts (suppressed: 0 from 0)
(base) tdhock@maude-MacBookPro:~/projects/LOPART-paper$ 
```
and with the supp file that false positive is suppressed:
```
(base) tdhock@maude-MacBookPro:~/projects/LOPART-paper$ R --vanilla -d "valgrind --suppressions=$HOME/R/wcsrtombs.supp" -e 'extSoftVersion()'
==5541== Memcheck, a memory error detector
==5541== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==5541== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==5541== Command: /home/tdhock/lib/R/bin/exec/R --vanilla -e extSoftVersion()
==5541== 

R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> extSoftVersion()
                                             zlib 
                                         "1.2.11" 
                                            bzlib 
                             "1.0.6, 6-Sept-2010" 
                                               xz 
                                          "5.2.2" 
                                             PCRE 
                               "10.31 2018-02-12" 
                                              ICU 
                                           "60.2" 
                                              TRE 
                        "TRE 0.8.0 R_fixes (BSD)" 
                                            iconv 
                                     "glibc 2.27" 
                                         readline 
                                            "7.0" 
                                             BLAS 
"/usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1" 
> 
> 
==5541== 
==5541== HEAP SUMMARY:
==5541==     in use at exit: 40,492,984 bytes in 9,170 blocks
==5541==   total heap usage: 19,784 allocs, 10,614 frees, 62,951,480 bytes allocated
==5541== 
==5541== LEAK SUMMARY:
==5541==    definitely lost: 0 bytes in 0 blocks
==5541==    indirectly lost: 0 bytes in 0 blocks
==5541==      possibly lost: 0 bytes in 0 blocks
==5541==    still reachable: 40,492,984 bytes in 9,170 blocks
==5541==                       of which reachable via heuristic:
==5541==                         newarray           : 4,264 bytes in 1 blocks
==5541==         suppressed: 0 bytes in 0 blocks
==5541== Rerun with --leak-check=full to see details of leaked memory
==5541== 
==5541== For counts of detected and suppressed errors, rerun with: -v
==5541== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 46 from 1)
(base) tdhock@maude-MacBookPro:~/projects/LOPART-paper$
```

**Comment by akhikolla** [comment]
@tdhock I have added the suppressions argument to the run line and the output looks the same even when I run the executable without that argument:
I don't see any false positives in Valgrind output even when the input size is  6. Earlier I used to get them but then after I changed the RInside call from RInside(argc,argv) to RInside(). I got rid of those false positives.

Run line: **valgrind --tool=memcheck --leak-check=yes --suppressions=/home/akhila/R/RcppDeepState/inst/testfiles/testSAN/wcsrtombs.supp ./use_after_deallocate_DeepState_TestHarness --fuzz > /home/akhila/R/RcppDeepState/inst/testfiles/testSAN/use_after_deallocate_log 2>&1**

==4178== Memcheck, a memory error detector
==4178== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4178== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==4178== Command: ./use_after_deallocate_DeepState_TestHarness --fuzz
==4178== 
INFO: Starting fuzzing
WARNING: No seed provided; using 1592517361
WARNING: No test specified, defaulting to first test defined (use_after_deallocate_random_datatypes_rcpp_use_after_deallocate_test)
size values: 6
==4179== Invalid read of size 1
==4179==    at 0x418234: rcpp_use_after_deallocate(int) (use_after_deallocate.cpp:12)
==4179==    by 0x407F5D: DeepState_Test_use_after_deallocate_random_datatypes_rcpp_use_after_deallocate_test() (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x407E38: DeepState_Run_use_after_deallocate_random_datatypes_rcpp_use_after_deallocate_test() (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x405CC3: DeepState_RunTest.isra.6 (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x40DF2A: DeepState_FuzzOneTestCase (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x40E03F: DeepState_Fuzz (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x40629D: main (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==  Address 0xc071ac5 is 5 bytes inside a block of size 6 free'd
==4179==    at 0x4C3173B: operator delete[](void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4179==    by 0x418233: rcpp_use_after_deallocate(int) (use_after_deallocate.cpp:11)
==4179==    by 0x407F5D: DeepState_Test_use_after_deallocate_random_datatypes_rcpp_use_after_deallocate_test() (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x407E38: DeepState_Run_use_after_deallocate_random_datatypes_rcpp_use_after_deallocate_test() (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x405CC3: DeepState_RunTest.isra.6 (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x40DF2A: DeepState_FuzzOneTestCase (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x40E03F: DeepState_Fuzz (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x40629D: main (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==  Block was alloc'd at
==4179==    at 0x4C3089F: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4179==    by 0x418228: rcpp_use_after_deallocate(int) (use_after_deallocate.cpp:10)
==4179==    by 0x407F5D: DeepState_Test_use_after_deallocate_random_datatypes_rcpp_use_after_deallocate_test() (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x407E38: DeepState_Run_use_after_deallocate_random_datatypes_rcpp_use_after_deallocate_test() (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x405CC3: DeepState_RunTest.isra.6 (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x40DF2A: DeepState_FuzzOneTestCase (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x40E03F: DeepState_Fuzz (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179==    by 0x40629D: main (in /home/akhila/R/RcppDeepState/use_after_deallocate_DeepState_TestHarness)
==4179== 
==4179== 
==4179== HEAP SUMMARY:
==4179==     in use at exit: 50,292,267 bytes in 9,713 blocks
==4179==   total heap usage: 27,722 allocs, 18,009 frees, 85,999,860 bytes allocated
==4179== 
==4179== LEAK SUMMARY:
==4179==    definitely lost: 0 bytes in 0 blocks
==4179==    indirectly lost: 0 bytes in 0 blocks
==4179==      possibly lost: 0 bytes in 0 blocks
==4179==    still reachable: 50,292,267 bytes in 9,713 blocks
==4179==                       of which reachable via heuristic:
==4179==                         newarray           : 4,264 bytes in 1 blocks
==4179==         suppressed: 0 bytes in 0 blocks
==4179== Reachable blocks (those to which a pointer was found) are not shown.
==4179== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==4179== 
==4179== For counts of detected and suppressed errors, rerun with: -v
==4179== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

**Comment by tdhock** [comment]
ok well that is fine thanks for investigating
