### ISSUE TITLE
remove .Rproj.user

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#9]
that directory is Rstudio-specific and should not be included in the git repo.
you should use `git rm` to remove that directory.
then put .Rproj.user in the RcppDeepState/.gitignore file so that it won't be included/added in any future commits.

**Comment by akhikolla** [comment]
@tdhock please refer to the latest commit on GitHub - https://github.com/akhikolla/RcppDeepState 
As suggested removed .Rproj.user using git rm and added that to gitignore.

**Comment by tdhock** [comment]
great thx
